### ISSUE TITLE
g-code file don't load

### ISSUE THREAD

**Issue by eruizmay** [alvarogimenez/g-code-utils#1]
Hello,

I'm trying to load a g-code file with the File->Open  menu but it doesn't load
I'm using the 64 bit version on WIN10

Please find the file attached the gcode file
[Gerber_BottomLayer.nc.txt](https://github.com/alvarogimenez/g-code-utils/files/6788594/Gerber_BottomLayer.nc.txt)

**Comment by alvarogimenez** [comment]
Thanks for the report! I'll fix it and upload a new release in the next few hours.

**Comment by alvarogimenez** [comment]
I released version 1.0.1 with the bug fix. You can download it from the [releases section](https://github.com/alvarogimenez/g-code-utils/releases). The attached G-Code now loads and is correctly transposed! Thanks :)

**Comment by eruizmay** [comment]
> I released version 1.0.1 with the bug fix. You can download it from the [releases section](https://github.com/alvarogimenez/g-code-utils/releases). The attached G-Code now loads and is correctly transposed! Thanks :)

Thank you!!
