### ISSUE TITLE
Youtube quitó tus vídeos

### ISSUE THREAD

**Issue by Pastitas** [alvarogimenez/g-code-utils#3]
Buenas, te contacto por aquí porque me parece el lugar más adecuado. Los vídeos de youtube en los que referencias el uso de esta herramienta han sido eliminados, estoy seguro de ya lo sabes pero querría saber si planeas volver a subirlos o si fuiste tu el que los retiró.

Gracias por las herramientas y las guías, ando haciendo ahora justo las modificaciones a una cnc para probar tu método.
Tengo también algunas ideas de como se podría hacer  electro-metalizado de los taladros  y la máscara de soldadura en una misma placa.

**Comment by alvarogimenez** [comment]
Youtube ha cancelado mi canal por supuestamente infringir las normas de Spam y contenido engañoso siendo esto obviamente incorrecto. He recibido un correo diciendo que se elimina definitivamente mi canal. He realizado una apelación y la respuesta de Youtube es que "mantienen su decisión" y no me permiten realizar ninguna otra apelación ni aportan ninguna otra información. Estoy ahora mismo en shock... Intentaré que Youtube me atienda y rectifique pero no tengo mucha esperanza ahora mismo.

**Comment by Pastitas** [comment]
Joder no se puede uno fiar de estas empresas, que putada, mucha suerte. 
Aquí tienes una búsqueda en LinkedIn de gente que curre en youtube de españa, a ver si tirando por ahí consigues algo
https://www.linkedin.com/search/results/people/?currentCompany=%5B%221441%22%5D&geoUrn=%5B%22105646813%22%5D&keywords=youtube&origin=FACETED_SEARCH&sid=LwU

**Comment by alvarogimenez** [comment]
Muchas gracias! Ojalá desde Youtube reconozcan el error y devuelvan el canal pero mucho me temo que pinta mal la cosa (Respuestas impersonales y automatizadas de bots). Si finalmente no lo hacen tendré que empezar de cero subiendo el contenido a un nuevo canal y lo publicaré por aquí y en mi web para los que pudierais estar interesados.
