### ISSUE TITLE
gcode utils error de trasposición

### ISSUE THREAD

**Issue by jelsesser** [alvarogimenez/g-code-utils#4]
Al emplear el software de trasposición del Gcode (G-Code Utils x64) y trasponer cualquier código, genera un ángulo de rotación de 68° sea cual fuere el cambio de coordenadas.
Probado con cualquier valor de coordenadas, incluso sin cambiar las mismas.

Trasposición sin cambiar coordenadas
![mismas coordenadas](https://user-images.githubusercontent.com/89048756/155803648-b33e1c1c-7e33-4300-80f1-a54dd41fd38b.JPG)

Trasposición con coordenadas desplazada
![coordenadas diferentes](https://user-images.githubusercontent.com/89048756/155803727-b9fe8023-018b-43fd-9ce0-502d41c6a811.JPG)
s

**Comment by jelsesser** [comment]
A disposición en lo que pueda ayudar para corregir el error.
Gracias!!

**Comment by alvarogimenez** [comment]
Mañana sin falta le echo un vistazo y te digo algo!

**Comment by alvarogimenez** [comment]
El error que tienes es conocido, ya fue reportado y corregido en la versión 1.0.1. Asegúrate de descargar la última versión del software en la sección de Releases:
https://github.com/alvarogimenez/g-code-utils/releases
Efectivamente era un problema de cálculo con las placas que no se encontraban centradas en el (0,0). He probado con la última versión del software y funciona correctamente! Un saludo 😀

**Comment by jelsesser** [comment]
Muchas gracias Álvaro! Procuraré descargar la última versión.
Saludos
