### ISSUE TITLE
Por favor añade una licencia al proyecto

### ISSUE THREAD

**Issue by rurigk** [alvarogimenez/g-code-utils#6]
Actualmente el proyecto "g-code-utils" no tiene una licencia por lo cual se asume es un proyecto de codigo cerrado y privado (aun estando en github y pudiendo ser descargado)

Por lo tanto no se puede usar, descargar, copiar, modificar, por lo tanto no se pueden hacer contrubuciones al codigo
Es de suma importancia que se incluya una licencia para permitir el uso legal de esta herramienta
Si tienes la intencion de que el codigo sea OpenSource o Software Libre (Son diferentes) debes especificarlo con una licencia

Antes de agregar una licencia todos los autores que hayan aportado codigo deberan aceptar la licencia escogida

Por que debes agregar una licencia?
Si no se agrega una licencia y alguien decidiera usar esta herramienta o modificar su codigo fuente podria verse afectada legalmente si los autores de esta herramienta decidieran iniciar un proceso legal por derechos de autor u otros motivos en contra de esa persona
[choosealicense.com/no-permission/
](https://choosealicense.com/no-permission/
)
Si no estas seguro que licencia elegir te recomiendo usar esta herramienta para determinar cual es tu mejor opcion [choosealicense.com](https://choosealicense.com/)

Por cierto tus videos han sido de mucha utilidad

**Comment by alvarogimenez** [comment]
Gracias @rurigk , era algo que tenía pendiente hacer pero nunca encontraba el momento, lo acabo de incluir.
