### ISSUE TITLE
Error al calcular

### ISSUE THREAD

**Issue by oscarren-mm** [alvarogimenez/g-code-utils#9]
cargo las coordenadas, y el recuadro narajan si lo calcula bien respecto al recuadro original azul, pero al momento de calcular se desfasa mucho.

![image](https://user-images.githubusercontent.com/99999208/197302826-308701ef-bead-4486-9f85-781f69e51ca2.png)

**Comment by alvarogimenez** [comment]
Hola! Creo que estás utilizando una versión antigua de la aplicación. Ese error debería estar solucionado en la última versión que puedes descargar desde aquí: 
https://github.com/alvarogimenez/g-code-utils/releases
Un saludo 😀

**Comment by oscarren-mm** [comment]
Gracias, funciona perfectamente con la versión mas reciente.

Saludos..
